[package]
name = "test_utils"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "devnet"
path = "src/bin/devnet.rs"

[dependencies]
alloy = { version = "0.3.6", features = ["full", "node-bindings"] }
bitcoind = "0.36.0"
eyre = "0.6.12"
tokio = {version="1.40.0", features=["full"]}
