[package]
name = "rift_py"
version = "0.1.0"
edition = "2021"

[lib]
name = "rift_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18.1", features = ["extension-module"] }
rift-lib = { path = "../circuits/lib" }
utils = { path = "../circuits/utils" }
